//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebSpaceMent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSpaceMentEntities1 : DbContext
    {
        public dbSpaceMentEntities1()
            : base("name=dbSpaceMentEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activities> Activities { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Favorites> Favorites { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Owners> Owners { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Rates> Rates { get; set; }
        public virtual DbSet<Spaces> Spaces { get; set; }
        public virtual DbSet<SubSpaces> SubSpaces { get; set; }
    }
}
