//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebSpaceMent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorites
    {
        public int FK_Favorite_to_Member { get; set; }
        public int FK_Favorite_to_Space { get; set; }
        public System.DateTime fCreated_at { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Spaces Spaces { get; set; }
    }
}
