
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace prjWebSpaceMent.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Members
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Members()
    {

        this.Activities = new HashSet<Activities>();

        this.Comments = new HashSet<Comments>();

        this.Favorites = new HashSet<Favorites>();

        this.Orders = new HashSet<Orders>();

        this.Orders1 = new HashSet<Orders>();

        this.Photos = new HashSet<Photos>();

        this.Rates = new HashSet<Rates>();

        this.Spaces = new HashSet<Spaces>();

    }


    public int mNumber { get; set; }

    public string mAccount { get; set; }

    public string mPassword { get; set; }

    public string mName { get; set; }

    public string mNickName { get; set; }

    public string mEmail { get; set; }

    public string mPhone { get; set; }

    public string mGender { get; set; }

    public string mTWid { get; set; }

    public System.DateTime mBirthday { get; set; }

    public int mPoint { get; set; }

    public System.DateTime mCreated_at { get; set; }

    public System.DateTime mUpdated_at { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Activities> Activities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Comments> Comments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Favorites> Favorites { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Orders> Orders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Orders> Orders1 { get; set; }

    public virtual Owners Owners { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Photos> Photos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rates> Rates { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Spaces> Spaces { get; set; }

}

}
