//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebSpaceMent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Rates = new HashSet<Rates>();
        }
    
        public int oNumber { get; set; }
        public string oStatus { get; set; }
        public Nullable<System.DateTime> oScheduledTime { get; set; }
        public Nullable<int> oScheduledHours { get; set; }
        public string oPaymentMode { get; set; }
        public string oPaymentStatus { get; set; }
        public string oDiscount { get; set; }
        public Nullable<decimal> oPayment { get; set; }
        public Nullable<System.DateTime> oCreate { get; set; }
        public Nullable<System.DateTime> oUpdate { get; set; }
        public Nullable<int> oFKtoUser { get; set; }
        public Nullable<int> oFKtoOwner { get; set; }
        public Nullable<int> oFKtoSpace { get; set; }
        public Nullable<int> oFKtoActivity { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual Members Members { get; set; }
        public virtual Members Members1 { get; set; }
        public virtual Spaces Spaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rates> Rates { get; set; }
    }
}
