//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebSpaceMent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSpaces
    {
        public int uNumber { get; set; }
        public string uName { get; set; }
        public string uIntro { get; set; }
        public Nullable<decimal> uRent { get; set; }
        public Nullable<decimal> uRate { get; set; }
        public Nullable<bool> uOpeningDays1 { get; set; }
        public Nullable<bool> uOpeningDays2 { get; set; }
        public Nullable<bool> uOpeningDays3 { get; set; }
        public Nullable<bool> uOpeningDays4 { get; set; }
        public Nullable<bool> uOpeningDays5 { get; set; }
        public Nullable<bool> uOpeningDays6 { get; set; }
        public Nullable<bool> uOpeningDays7 { get; set; }
        public Nullable<System.TimeSpan> uOpeningTime1 { get; set; }
        public Nullable<System.TimeSpan> uClosingTime1 { get; set; }
        public Nullable<System.TimeSpan> uOpeningTime2 { get; set; }
        public Nullable<System.TimeSpan> uClosingTime2 { get; set; }
        public Nullable<System.TimeSpan> uOpeningTime3 { get; set; }
        public Nullable<System.TimeSpan> uClosingTime3 { get; set; }
        public Nullable<System.DateTime> uCreate { get; set; }
        public Nullable<System.DateTime> uUpdate { get; set; }
        public Nullable<int> uFKtoSpace { get; set; }
    
        public virtual Spaces Spaces { get; set; }
    }
}
