//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace prjWebSpaceMent.Models.SPACEMENT
{

    public partial class Activities : XPLiteObject
    {
        int faNumber;
        [Key(true)]
        public int aNumber
        {
            get { return faNumber; }
            set { SetPropertyValue<int>(nameof(aNumber), ref faNumber, value); }
        }
        Members faFKtoMember;
        [Association(@"ActivitiesReferencesMembers")]
        public Members aFKtoMember
        {
            get { return faFKtoMember; }
            set { SetPropertyValue<Members>(nameof(aFKtoMember), ref faFKtoMember, value); }
        }
        Spaces faFKtoSpace;
        [Association(@"ActivitiesReferencesSpaces")]
        public Spaces aFKtoSpace
        {
            get { return faFKtoSpace; }
            set { SetPropertyValue<Spaces>(nameof(aFKtoSpace), ref faFKtoSpace, value); }
        }
        string faName;
        [Size(50)]
        public string aName
        {
            get { return faName; }
            set { SetPropertyValue<string>(nameof(aName), ref faName, value); }
        }
        string faHeadCount;
        [Size(10)]
        public string aHeadCount
        {
            get { return faHeadCount; }
            set { SetPropertyValue<string>(nameof(aHeadCount), ref faHeadCount, value); }
        }
        string faType;
        [Size(10)]
        public string aType
        {
            get { return faType; }
            set { SetPropertyValue<string>(nameof(aType), ref faType, value); }
        }
        DateTime faSignUpTime;
        public DateTime aSignUpTime
        {
            get { return faSignUpTime; }
            set { SetPropertyValue<DateTime>(nameof(aSignUpTime), ref faSignUpTime, value); }
        }
        DateTime faHoldTime;
        public DateTime aHoldTime
        {
            get { return faHoldTime; }
            set { SetPropertyValue<DateTime>(nameof(aHoldTime), ref faHoldTime, value); }
        }
        decimal faFee;
        public decimal aFee
        {
            get { return faFee; }
            set { SetPropertyValue<decimal>(nameof(aFee), ref faFee, value); }
        }
        DateTime faCreatedat;
        public DateTime aCreatedat
        {
            get { return faCreatedat; }
            set { SetPropertyValue<DateTime>(nameof(aCreatedat), ref faCreatedat, value); }
        }
        DateTime faUpdatedat;
        public DateTime aUpdatedat
        {
            get { return faUpdatedat; }
            set { SetPropertyValue<DateTime>(nameof(aUpdatedat), ref faUpdatedat, value); }
        }
        [Association(@"OrdersReferencesActivities")]
        public XPCollection<Orders> OrdersCollection { get { return GetCollection<Orders>(nameof(OrdersCollection)); } }
    }

}
