//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace prjWebSpaceMent.Models.SPACEMENT
{

    public partial class Favorites : XPLiteObject
    {
        DateTime ffCreatedat;
        public DateTime fCreatedat
        {
            get { return ffCreatedat; }
            set { SetPropertyValue<DateTime>(nameof(fCreatedat), ref ffCreatedat, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("fFKtoMember")]
            public int fFKtoMember { get; set; }
            [Persistent("fFKtoSpace")]
            public int fFKtoSpace { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
