//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace prjWebSpaceMent.Models.SPACEMENT
{

    public partial class Members : XPLiteObject
    {
        int fmNumber;
        [Key(true)]
        public int mNumber
        {
            get { return fmNumber; }
            set { SetPropertyValue<int>(nameof(mNumber), ref fmNumber, value); }
        }
        string fmAccount;
        [Size(50)]
        public string mAccount
        {
            get { return fmAccount; }
            set { SetPropertyValue<string>(nameof(mAccount), ref fmAccount, value); }
        }
        string fmPassword;
        [Size(50)]
        public string mPassword
        {
            get { return fmPassword; }
            set { SetPropertyValue<string>(nameof(mPassword), ref fmPassword, value); }
        }
        string fmName;
        [Size(5)]
        public string mName
        {
            get { return fmName; }
            set { SetPropertyValue<string>(nameof(mName), ref fmName, value); }
        }
        string fmNickName;
        [Size(10)]
        public string mNickName
        {
            get { return fmNickName; }
            set { SetPropertyValue<string>(nameof(mNickName), ref fmNickName, value); }
        }
        string fmEmail;
        public string mEmail
        {
            get { return fmEmail; }
            set { SetPropertyValue<string>(nameof(mEmail), ref fmEmail, value); }
        }
        string fmPhone;
        [Size(20)]
        public string mPhone
        {
            get { return fmPhone; }
            set { SetPropertyValue<string>(nameof(mPhone), ref fmPhone, value); }
        }
        string fmGender;
        [Size(5)]
        public string mGender
        {
            get { return fmGender; }
            set { SetPropertyValue<string>(nameof(mGender), ref fmGender, value); }
        }
        string fmTWid;
        [Size(10)]
        public string mTWid
        {
            get { return fmTWid; }
            set { SetPropertyValue<string>(nameof(mTWid), ref fmTWid, value); }
        }
        DateTime fmBirthday;
        public DateTime mBirthday
        {
            get { return fmBirthday; }
            set { SetPropertyValue<DateTime>(nameof(mBirthday), ref fmBirthday, value); }
        }
        DateTime fmCreatedat;
        public DateTime mCreatedat
        {
            get { return fmCreatedat; }
            set { SetPropertyValue<DateTime>(nameof(mCreatedat), ref fmCreatedat, value); }
        }
        DateTime fmUpdatedat;
        public DateTime mUpdatedat
        {
            get { return fmUpdatedat; }
            set { SetPropertyValue<DateTime>(nameof(mUpdatedat), ref fmUpdatedat, value); }
        }
        bool fmOwner;
        public bool mOwner
        {
            get { return fmOwner; }
            set { SetPropertyValue<bool>(nameof(mOwner), ref fmOwner, value); }
        }
        [Association(@"ActivitiesReferencesMembers")]
        public XPCollection<Activities> ActivitiesCollection { get { return GetCollection<Activities>(nameof(ActivitiesCollection)); } }
        [Association(@"OrdersReferencesMembers")]
        public XPCollection<Orders> OrdersCollection { get { return GetCollection<Orders>(nameof(OrdersCollection)); } }
        [Association(@"OrdersReferencesMembers1")]
        public XPCollection<Orders> OrdersCollection1 { get { return GetCollection<Orders>(nameof(OrdersCollection1)); } }
        [Association(@"PhotosReferencesMembers")]
        public XPCollection<Photos> PhotosCollection { get { return GetCollection<Photos>(nameof(PhotosCollection)); } }
        [Association(@"RatesReferencesMembers")]
        public XPCollection<Rates> RatesCollection { get { return GetCollection<Rates>(nameof(RatesCollection)); } }
        [Association(@"SpacesReferencesMembers")]
        public XPCollection<Spaces> SpacesCollection { get { return GetCollection<Spaces>(nameof(SpacesCollection)); } }
    }

}
