//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace prjWebSpaceMent.Models.SPACEMENT
{

    public partial class Orders : XPLiteObject
    {
        int foNumber;
        [Key(true)]
        public int oNumber
        {
            get { return foNumber; }
            set { SetPropertyValue<int>(nameof(oNumber), ref foNumber, value); }
        }
        string foStatus;
        [Size(20)]
        public string oStatus
        {
            get { return foStatus; }
            set { SetPropertyValue<string>(nameof(oStatus), ref foStatus, value); }
        }
        DateTime foScheduledTime;
        public DateTime oScheduledTime
        {
            get { return foScheduledTime; }
            set { SetPropertyValue<DateTime>(nameof(oScheduledTime), ref foScheduledTime, value); }
        }
        int foScheduledHours;
        public int oScheduledHours
        {
            get { return foScheduledHours; }
            set { SetPropertyValue<int>(nameof(oScheduledHours), ref foScheduledHours, value); }
        }
        string foPaymentMode;
        [Size(10)]
        public string oPaymentMode
        {
            get { return foPaymentMode; }
            set { SetPropertyValue<string>(nameof(oPaymentMode), ref foPaymentMode, value); }
        }
        string foPaymentStatus;
        [Size(10)]
        public string oPaymentStatus
        {
            get { return foPaymentStatus; }
            set { SetPropertyValue<string>(nameof(oPaymentStatus), ref foPaymentStatus, value); }
        }
        string foDiscount;
        [Size(10)]
        public string oDiscount
        {
            get { return foDiscount; }
            set { SetPropertyValue<string>(nameof(oDiscount), ref foDiscount, value); }
        }
        decimal foPayment;
        public decimal oPayment
        {
            get { return foPayment; }
            set { SetPropertyValue<decimal>(nameof(oPayment), ref foPayment, value); }
        }
        DateTime foCreatedat;
        public DateTime oCreatedat
        {
            get { return foCreatedat; }
            set { SetPropertyValue<DateTime>(nameof(oCreatedat), ref foCreatedat, value); }
        }
        DateTime foUpdatedat;
        public DateTime oUpdatedat
        {
            get { return foUpdatedat; }
            set { SetPropertyValue<DateTime>(nameof(oUpdatedat), ref foUpdatedat, value); }
        }
        Members foFKtoUser;
        [Association(@"OrdersReferencesMembers1")]
        public Members oFKtoUser
        {
            get { return foFKtoUser; }
            set { SetPropertyValue<Members>(nameof(oFKtoUser), ref foFKtoUser, value); }
        }
        Members foFKtoOwner;
        [Association(@"OrdersReferencesMembers")]
        public Members oFKtoOwner
        {
            get { return foFKtoOwner; }
            set { SetPropertyValue<Members>(nameof(oFKtoOwner), ref foFKtoOwner, value); }
        }
        Spaces foFKtoSpace;
        [Association(@"OrdersReferencesSpaces")]
        public Spaces oFKtoSpace
        {
            get { return foFKtoSpace; }
            set { SetPropertyValue<Spaces>(nameof(oFKtoSpace), ref foFKtoSpace, value); }
        }
        Activities foFKtoActivity;
        [Association(@"OrdersReferencesActivities")]
        public Activities oFKtoActivity
        {
            get { return foFKtoActivity; }
            set { SetPropertyValue<Activities>(nameof(oFKtoActivity), ref foFKtoActivity, value); }
        }
        [Association(@"RatesReferencesOrders")]
        public XPCollection<Rates> RatesCollection { get { return GetCollection<Rates>(nameof(RatesCollection)); } }
    }

}
