//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace prjWebSpaceMent.Models.SPACEMENT
{

    public partial class Photos : XPLiteObject
    {
        int fpNumber;
        [Key(true)]
        public int pNumber
        {
            get { return fpNumber; }
            set { SetPropertyValue<int>(nameof(pNumber), ref fpNumber, value); }
        }
        string fpUrl;
        [Size(50)]
        public string pUrl
        {
            get { return fpUrl; }
            set { SetPropertyValue<string>(nameof(pUrl), ref fpUrl, value); }
        }
        DateTime fpCreatedat;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime pCreatedat
        {
            get { return fpCreatedat; }
            set { SetPropertyValue<DateTime>(nameof(pCreatedat), ref fpCreatedat, value); }
        }
        DateTime fpUpdatedat;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime pUpdatedat
        {
            get { return fpUpdatedat; }
            set { SetPropertyValue<DateTime>(nameof(pUpdatedat), ref fpUpdatedat, value); }
        }
        Members fpFKtoMember;
        [Association(@"PhotosReferencesMembers")]
        public Members pFKtoMember
        {
            get { return fpFKtoMember; }
            set { SetPropertyValue<Members>(nameof(pFKtoMember), ref fpFKtoMember, value); }
        }
        Spaces fpFKtoSpace;
        [Association(@"PhotosReferencesSpaces")]
        public Spaces pFKtoSpace
        {
            get { return fpFKtoSpace; }
            set { SetPropertyValue<Spaces>(nameof(pFKtoSpace), ref fpFKtoSpace, value); }
        }
    }

}
