//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace prjWebSpaceMent.Models.SPACEMENT
{

    public partial class SubSpaces : XPLiteObject
    {
        int fuNumber;
        [Key(true)]
        public int uNumber
        {
            get { return fuNumber; }
            set { SetPropertyValue<int>(nameof(uNumber), ref fuNumber, value); }
        }
        string fuName;
        [Size(50)]
        public string uName
        {
            get { return fuName; }
            set { SetPropertyValue<string>(nameof(uName), ref fuName, value); }
        }
        string fuIntro;
        [Size(500)]
        public string uIntro
        {
            get { return fuIntro; }
            set { SetPropertyValue<string>(nameof(uIntro), ref fuIntro, value); }
        }
        decimal fuRent;
        public decimal uRent
        {
            get { return fuRent; }
            set { SetPropertyValue<decimal>(nameof(uRent), ref fuRent, value); }
        }
        decimal fuRate;
        public decimal uRate
        {
            get { return fuRate; }
            set { SetPropertyValue<decimal>(nameof(uRate), ref fuRate, value); }
        }
        bool fuOpeningDays1;
        public bool uOpeningDays1
        {
            get { return fuOpeningDays1; }
            set { SetPropertyValue<bool>(nameof(uOpeningDays1), ref fuOpeningDays1, value); }
        }
        bool fuOpeningDays2;
        public bool uOpeningDays2
        {
            get { return fuOpeningDays2; }
            set { SetPropertyValue<bool>(nameof(uOpeningDays2), ref fuOpeningDays2, value); }
        }
        bool fuOpeningDays3;
        public bool uOpeningDays3
        {
            get { return fuOpeningDays3; }
            set { SetPropertyValue<bool>(nameof(uOpeningDays3), ref fuOpeningDays3, value); }
        }
        bool fuOpeningDays4;
        public bool uOpeningDays4
        {
            get { return fuOpeningDays4; }
            set { SetPropertyValue<bool>(nameof(uOpeningDays4), ref fuOpeningDays4, value); }
        }
        bool fuOpeningDays5;
        public bool uOpeningDays5
        {
            get { return fuOpeningDays5; }
            set { SetPropertyValue<bool>(nameof(uOpeningDays5), ref fuOpeningDays5, value); }
        }
        bool fuOpeningDays6;
        public bool uOpeningDays6
        {
            get { return fuOpeningDays6; }
            set { SetPropertyValue<bool>(nameof(uOpeningDays6), ref fuOpeningDays6, value); }
        }
        bool fuOpeningDays7;
        public bool uOpeningDays7
        {
            get { return fuOpeningDays7; }
            set { SetPropertyValue<bool>(nameof(uOpeningDays7), ref fuOpeningDays7, value); }
        }
        DateTime fuCreatedat;
        public DateTime uCreatedat
        {
            get { return fuCreatedat; }
            set { SetPropertyValue<DateTime>(nameof(uCreatedat), ref fuCreatedat, value); }
        }
        DateTime fuUpdatedat;
        public DateTime uUpdatedat
        {
            get { return fuUpdatedat; }
            set { SetPropertyValue<DateTime>(nameof(uUpdatedat), ref fuUpdatedat, value); }
        }
        Spaces fuFKtoSpace;
        [Association(@"SubSpacesReferencesSpaces")]
        public Spaces uFKtoSpace
        {
            get { return fuFKtoSpace; }
            set { SetPropertyValue<Spaces>(nameof(uFKtoSpace), ref fuFKtoSpace, value); }
        }
    }

}
