//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebSpaceMent
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Spaces
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spaces()
        {
            this.Activities = new HashSet<Activities>();
            this.Favorites = new HashSet<Favorites>();
            this.Orders = new HashSet<Orders>();
            this.Photos = new HashSet<Photos>();
            this.Rates = new HashSet<Rates>();
            this.SubSpaces = new HashSet<SubSpaces>();
        }
    
        
        [DisplayName("序號")]
        public int sNumber { get; set; }

        [DisplayName("場地名稱")]
        public string sName { get; set; }

        [DisplayName("場地類型")]
        public string sType { get; set; }

        [DisplayName("地址")]
        public string sAddr { get; set; }

        [DisplayName("聯絡電話")]
        public string sPhone { get; set; }

        [DisplayName("樓層")]
        public string sFloor { get; set; }

        [DisplayName("高度")]
        public string sHeight { get; set; }

        [DisplayName("面積")]
        public string sArea { get; set; }

        [DisplayName("可容納人數")]
        public string sCapacity { get; set; }

        [DisplayName("費用")]
        public decimal sRent { get; set; }

        [DisplayName("費率")]
        public decimal sRate { get; set; }

        [DisplayName("簡介")]
        public string sIntro { get; set; }

        [DisplayName("營業時間")]
        public string sOpeningTime { get; set; }

        [DisplayName("場地安全")]
        public string sSecurity { get; set; }

        [DisplayName("交通特色")]
        public string sTraffic { get; set; }

        [DisplayName("建立時間")]
        public System.DateTime sCreated_at { get; set; }

        [DisplayName("更新時間")]
        public System.DateTime sUpdated_at { get; set; }

        [DisplayName("會員編號")]
        public Nullable<int> FK_Space_to_Owner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorites> Favorites { get; set; }
        public virtual Members Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photos> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rates> Rates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubSpaces> SubSpaces { get; set; }
    }
}
